### PR TITLE
change the default values for NBth.R and NBthmDE.R

### PR DESCRIPTION
**Pull request by zhiiiyang**
## Unit tests 
image

## devtools::check() results
image

## BiocCheck::BiocCheck() results

image

### CODE REVIEW

**Comment by zhiiiyang** [comment]
I wouldn't worry about the warnings cuz they existed before only associated with the local environment.

**Review by NicoleEO — APPROVED** [review]
Looks good to me. Can you just double-check the vignette runs without error?

**Review by yangleicq — APPROVED** [review]

**Comment by yangleicq** [comment]
Looks good to me.

**Comment by zhiiiyang** [comment]
@NicoleEO, @yangleicq 
See vignette building resutls 

**─  installing the package to build vignettes
✓  creating vignettes (7m 5.8s)**

```
> devtools::check(vignettes = TRUE)
ℹ Updating GeoDiff documentation
ℹ Loading GeoDiff
Warning: The existing 'NAMESPACE' file was not generated by roxygen2, and will not be overwritten.
Warning: The existing 'NAMESPACE' file was not generated by roxygen2, and will not be overwritten.
── Building ────────────────────────────────────────────────────────────────────────────────────────────── GeoDiff ──
Setting env vars:
• CFLAGS    : -Wall -pedantic -fdiagnostics-color=always
• CXXFLAGS  : -Wall -pedantic -fdiagnostics-color=always
• CXX11FLAGS: -Wall -pedantic -fdiagnostics-color=always
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✓  checking for file ‘/home/rstudio/NAS_data/zyang/Rpackages/GeoDiff/DESCRIPTION’ (1.4s)
─  preparing ‘GeoDiff’: (2.8s)
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  installing the package to build vignettes
✓  creating vignettes (7m 5.8s)
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘GeoDiff_0.99.7.tar.gz’ (1.2s)

```

**Pull request merged**
