### PR TITLE
merge after bioccheck()

### PR DESCRIPTION
**Pull request by ned-procogia**
@zhiiiyang I just ran BiocCheck() - I had to change things a little bit to make it work (just a bit of syntax in my code, nothing major).

### CODE REVIEW

**Comment by zhiiiyang** [comment]
I am tagging @yangleicq to review this issue.

**Comment by zhiiiyang** [comment]
@rvitancol @NicoleEO, could you tell Ned what other changes are needed on specs and reqs per our discussion on standup today?

**Comment by rvitancol** [comment]
@ned-procogia Can you also update the Reqs and Specs and corresponding unit tests for the changes that you made? One way to check what these are is to check the following: 1. functions where Inputs and outputs were changed. 2. Functions where the calculations were changed. 3. And also add additional unit test when necessary for the code you added.  Thanks.

**Comment by ned-procogia** [comment]
@rvitancol I will update the reqs and specs then send another pull request

**Comment by zhiiiyang** [comment]
@ned-procogia, a quick reminder, you don't have to close the PR every time we have any new requests. You can just keep pushing the changes in the same PR and make a comment about your changes.

**Comment by ned-procogia** [comment]
@zhiiiyang I didn't know that. Will bear that in mind, thanks!

**Pull request closed without merging**
